# Setup
title: Gengar's House
description: Pokemon and more!
url: https://risingtoast.github.io
avatar: /pro_gengar.png
paginate: 5
permalink: pretty
cover_image: /bg_gengar.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - not-pure-poole

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
logo: logo.png
social:
  name: RisingToast
google_site_verification: xxxxx
lang: ko

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: RisingToast
  url: https://github.com/RisingToast/
  email: kt6267134@gmail.com
